version: '3'
services:
  mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cr3tPa55w0rd      
      - MYSQL_DATABASE=userdb
    volumes:
      - dbVolume:/var/lib/mysql
  flask:
    image: flask-app
    entrypoint: /webapp/entrypoint.sh
    ports: 
      - 5000:5000
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DATABASE_NAME=userdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=S3cr3tPa55w0rd      
      - DATABASE_HOST=mysql
volumes:
  dbVolume:      